import { type NextPage } from "next";
import Link from "next/link";
import Head from "next/head";
import {
  useUser,
  SignInButton,
  SignedOut,
  SignUpButton,
  UserButton,
} from "@clerk/nextjs";

import { api } from "~/utils/api";

const Home: NextPage = () => {
  const user = useUser();
  const { data } = api.posts.getAll.useQuery();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="layout">
        <div className="">
          {!user.isSignedIn && <SignInButton />}
          {!!user.isSignedIn && <UserButton />}
        </div>
        <div className="">
          {data?.map((post) => (
            <div className="" key={post.id}>
              {post.content}
            </div>
          ))}
        </div>
      </main>
    </>
  );
};

export default Home;
