import { type NextPage } from "next";
import Link from "next/link";
import Head from "next/head";
import {
  useUser,
  SignInButton,
  SignedOut,
  SignUpButton,
  UserButton,
} from "@clerk/nextjs";

import { api } from "~/utils/api";

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "Constantine" });
  const user = useUser();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="layout">
        <div className="">
          {!user.isSignedIn && <SignInButton />}
          {!!user.isSignedIn && <UserButton />}
        </div>
      </main>
    </>
  );
};

export default Home;
