import Head from "next/head";
import Link from "next/link";
import * as React from "react";

export const Layout = ({
  children,
  ...rest
}: {
  children: React.ReactNode;
}) => {
  return (
    <React.Fragment>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="layout text-[hsl(280,100%,70%)]">
        <nav className="fixed text-center">
          <ul className="flex gap-6 text-center font-semibold">
            <li className="py-5">
              <Link href="/">Home</Link>
            </li>
            <li className="py-5">
              <Link href="/about">About</Link>
            </li>
          </ul>
        </nav>
      </header>
      <main className="min-h-screen bg-[#010102]" {...rest}>
        {children}
      </main>
    </React.Fragment>
  );
};
